version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: test-docker-frontend:latest 
    ports:
      - "5711:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: test-docker-backend:latest
    ports:
      - "3007:3007"
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


